version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - mynetwork

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080
    networks:
      - mynetwork

networks:
  mynetwork:
